---
root: true
extends: ["eslint:recommended", "google"]
env:
  es6: true
  browser: true

rules:
  indent:
    - warn
    - 4
  prefer-destructuring: off
  brace-style:
    - 2
    - stroustrup
    - allowSingleLine: false
  require-jsdoc: 0
  no-console: 0

parserOptions:
  sourceType: module


